### ISSUE TITLE
Tira 248

### ISSUE THREAD

**Issue by qw3rthz** [nasciiboy/tira-ecol#1]
En archive.org está la tira en inglés...creo que es ésta.
![tiraecol_en-247](https://user-images.githubusercontent.com/35897473/131849018-c47dc035-263b-464f-8f37-decab29169a5.png)

**Comment by Jakeukalane** [comment]
Esta es la que he visto yo: http://web.archive.org/web/20180610142138im_/http://www.tiraecol.net/modules/comic/cache/images/tiraecol-153.png
contexto: http://web.archive.org/web/20180610141956/http://www.tiraecol.net/modules/comic/comic.php?content_id=153&mode=flat&order=0

**Comment by opor** [comment]
En archive.org encontré la misma tira en español. 
![image](https://user-images.githubusercontent.com/1443638/132268539-e835ae60-4c96-4215-b713-2e143dd4393f.png)

Tiene el número 247 en el nombre del archivo: https://web.archive.org/web/20070613105146if_/http://www.tiraecol.net/modules/comic/cache/images/tiraecol-247.png

El título "Requerimientos exagerados" tiene sentido para esta tira. En el archivo de las tiras estaba entre "El búho se lleva la del pulpo" y "En caso de emergencia", que son las tiras 247 y 249. El archivo con los títulos se puede ver en https://web.archive.org/web/20110713110540/http://www.tiraecol.net/modules/comic/archive.php

**Comment by nasciiboy** [comment]
lo que me hubiese ahorrado de tiempo si antes revisara este comentario en lugar del siguiente... ja, ja

gracias por la ayuda, esta y la siguiente son las tiras faltantes. Lo subo al repo en cuanto vea como es la nueva autentificacion de github...
