### ISSUE TITLE
Tira 251?

### ISSUE THREAD

**Issue by qw3rthz** [nasciiboy/tira-ecol#2]
![tiraecol_en-249](https://user-images.githubusercontent.com/35897473/131849958-6f335126-ee82-44cc-8be8-a55241eb461c.png)

**Comment by Jakeukalane** [comment]
Esta es la que he visto yo: http://web.archive.org/web/20180610141940im_/http://www.tiraecol.net/modules/comic/cache/images/tiraecol-150.png

Contexto: http://web.archive.org/web/20180610141956/http://www.tiraecol.net/modules/comic/comic.php?content_id=150&mode=flat&order=0

**Comment by nasciiboy** [comment]
por como realice la copia, las imagen que has visto esta incluida y numerada como estaba en el servidor, tiraecol-150.png... pero segun el contexto seria la 251

a su ves, difiere al contenido de la que esta en ingles y que con una busqueda visual no se encuentra en el repo

... parece que borre el correo dende pedia permiso a Javier, pero creo haberle preguntado sobre las imagenes faltantes y me comento (creo) que solo tenia lo del servidor

mmm, creo que con la numeracion poco se puede hacer, lo "mas fiel" al contenido original seria visitar archive.org o hacer una copia estatica "limpia" con comentarios y poco mas

si encuentras la imagen en español con gusto la agrego, otra medio solucion completista seria agregar una carpeta con las tiras en ingles, supongo

**Comment by opor** [comment]
Diría que la tira 251 es esta:
![image](https://user-images.githubusercontent.com/1443638/132268993-2341fb75-0ea8-47bf-ab70-2c6a2362a434.png)

En archive.org el nombre del fichero tiene el número 250:
https://web.archive.org/web/20071017155149im_/http://www.tiraecol.net/modules/comic/cache/images/tiraecol-250.png

Además, el título de la tira entre la 250 y la 252 es "Mal ganar", que tiene sentido para esta tira.
Los títulos se pueden ver aquí: https://web.archive.org/web/20110713110540/http://www.tiraecol.net/modules/comic/archive.php

**Comment by opor** [comment]
Por cierto, la tira del primer mensaje en español es la número 210.

**Comment by opor** [comment]
La tira del primer mensaje ya está en español en el repositorio. Es la número 210.

**Comment by nasciiboy** [comment]
disculpa la tardansa, no reviso la pc diario...

es verdad la tira del primer mensaje esta como indicas

sobre la 251 "Mal ganar", parece que en algun momento la imagen dejo de aparecer como se puede ver aca 

https://web.archive.org/web/20100703034244/http://www.tiraecol.net/modules/comic/comic.php?content_id=251

sin embargo movierdose por las fechas la actual 250 anteriormente era la 249

https://web.archive.org/web/20071018221949/http://www.tiraecol.net/modules/comic/comic.php?content_id=249

y la posteriormente perdida 251, la 250

https://web.archive.org/web/20071017155125/http://www.tiraecol.net/modules/comic/comic.php?content_id=250

finalmente moviendose por el carrete en esa fecha de captura, la tambien perdida 248, seria 

https://web.archive.org/web/20071018152824/http://www.tiraecol.net/modules/comic/comic.php?content_id=247

**Comment by Jakeukalane** [comment]
Si ya está solucionado quizás habría que borrar esta línea: https://github.com/nasciiboy/tira-ecol/pull/4

Si no es así, deniega el pull request, obviamente.

**Comment by nasciiboy** [comment]
listo
